server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  # NRF Logs
  - job_name: nrf
    static_configs:
      - targets:
          - localhost
        labels:
          job: nrf
          nf_type: NRF
          __path__: /tmp/nrf.log
    pipeline_stages:
      - json:
          expressions:
            level: level
            msg: msg
            caller: caller
            ts: ts
      - labels:
          level:
      - timestamp:
          source: ts
          format: Unix
      - output:
          source: msg

  # UDR Logs
  - job_name: udr
    static_configs:
      - targets:
          - localhost
        labels:
          job: udr
          nf_type: UDR
          __path__: /tmp/udr.log
    pipeline_stages:
      - json:
          expressions:
            level: level
            msg: msg
      - labels:
          level:

  # UDM Logs
  - job_name: udm
    static_configs:
      - targets:
          - localhost
        labels:
          job: udm
          nf_type: UDM
          __path__: /tmp/udm.log
    pipeline_stages:
      - json:
          expressions:
            level: level
            msg: msg
      - labels:
          level:

  # AUSF Logs
  - job_name: ausf
    static_configs:
      - targets:
          - localhost
        labels:
          job: ausf
          nf_type: AUSF
          __path__: /tmp/ausf.log
    pipeline_stages:
      - json:
          expressions:
            level: level
            msg: msg
      - labels:
          level:

  # AMF Logs
  - job_name: amf
    static_configs:
      - targets:
          - localhost
        labels:
          job: amf
          nf_type: AMF
          __path__: /tmp/amf.log
    pipeline_stages:
      - json:
          expressions:
            level: level
            msg: msg
      - labels:
          level:

  # SMF Logs
  - job_name: smf
    static_configs:
      - targets:
          - localhost
        labels:
          job: smf
          nf_type: SMF
          __path__: /tmp/smf.log
    pipeline_stages:
      - json:
          expressions:
            level: level
            msg: msg
      - labels:
          level:

  # UPF Logs
  - job_name: upf
    static_configs:
      - targets:
          - localhost
        labels:
          job: upf
          nf_type: UPF
          __path__: /tmp/upf.log
    pipeline_stages:
      - json:
          expressions:
            level: level
            msg: msg
      - labels:
          level:
